// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://covypzsejvnsnyttfhcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvdnlwenNlanZuc255dHRmaGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NzE5MDYsImV4cCI6MjA2OTI0NzkwNn0.phpqMX0amOwV0eBTC_H4MqMP9oM6Efy0u8UXJh0xwr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});